# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 130d8d2d5242b1281319b1fbf518bb47e7ab6413d0d09d707b4b3c82524644350c567b7422086853a60f8c67942d5825b835db74e77e86b1174d63618d000357

test:
  secret_key_base: ac2bd1b93bc74cf1b105e45e16986471dfa87b99670263b4a2549abb876f6bff03a8b7360425456643f17683448a8a2ce08ff7fae9f38f6b225a24e71c3c8876

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
